### ISSUE TITLE
How do I deploy the latest disclosure-backend master?

### ISSUE THREAD

**Issue by adborden** [opencalifornia/disclosure-cookbook#2]
Is the `run.sh` for deploying the latest code? The README implies it's only for the initial configuration, but I'm pretty sure chef is smart about things :)

**Comment by tdooner** [comment]
`run.sh` is for deploying configuration changes (in this repo)... as for deploying the backend, there is a script for that purpose. Check the README of the disclosure-backend for more information ;)

**Comment by adborden** [comment]
Got it, thanks!
